name: testSite
version: 1.0.01
summary: Simple Test Python Website
description: |
  Writing a node will exectue the SQL statement on the SQLite database. Reading returns the result of the last succesful operation. 
base: core18
confinement: strict
grade: stable

architectures:
  - build-on: amd64
  #- build-on: arm64
  
apps:
  provider:
    command: main.py
    plugs:
      - network
    daemon: simple
    passthrough:   
      restart-condition: always
      restart-delay: 10s

parts:
  provider:
    plugin: python
    python-version: python3
    source: .
    python-packages:
      - ./whl/Flask-2.0.2-py3-none-any.whl

plugs:
  datalayer:
    interface: content
    content: datalayer
    target: $SNAP_DATA/.datalayer